### ISSUE TITLE
Encounter Reward permanently stuck bug

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#1]
Sometimes a glitch happens when after encounter the script tries to choose encounter reward too quickly, resulting in it getting stuck permanently unable to progress further.
By the way, the program is AMAZING except for a few glitches, thank you for your work!

Here's the video:
https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/c3b57c28-c0a4-4e4f-920e-3c5b09904b1d

**Comment by KIYI671** [comment]
> Sometimes a glitch happens when after encounter the script tries to choose encounter reward too quickly, resulting in it getting stuck permanently unable to progress further. By the way, the program is AMAZING except for a few glitches, thank you for your work!
> 
> Here's the video: https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/c3b57c28-c0a4-4e4f-920e-3c5b09904b1d

The following text was generated using translation software:

Thank you for your suggestion, this issue has been fixed, please go to release and download the new version to overwrite it. (Note: The file “config.yaml” holds the settings you saved when using the script, please do not overwrite it if you don't want to reconfigure the mirror dungeon team)
Regarding the Mirror Dungeon's team order settings, when you close the script and reopen it, the team order may be messed up, please try to close all the teams and reopen it. This bug was found before, but I've been refreshing my computer basics lately, so I haven't had time to fix it.
Thank you for recognizing and supporting my project, and I wish you the best of luck in using this script to reduce the rather uninteresting and repetitive content in the game, and to better enjoy the game's plot, performances, and mechanics.

Translated with DeepL.com (free version)
