### ISSUE TITLE
AALC might be broken after the update

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#15]
I don't know if it's my problem or it really broke after the update, but the program keeps opening and closing Settings menu infinitely now

**Comment by KIYI671** [comment]
Found the reason, please go to release to check.
Because the changes are too small, no new version will be released, please do it yourself.
It is expected that this judgment logic will be replaced in the next version of the script, and the next version is expected to be released after the next mirror dungeon update.

**Comment by arraf270** [comment]
> Found the reason, please go to release to check. Because the changes are too small, no new version will be released, please do it yourself. It is expected that this judgment logic will be replaced in the next version of the script, and the next version is expected to be released after the next mirror dungeon update.

Thank you!
