### ISSUE TITLE
Issue with multiple ego gift passive

### ISSUE THREAD

**Issue by misha1246** [KIYI671/AhabAssistantLimbusCompany#43]
When you confirm with 1/2 ego gifts, the game will ask if you want to pick another ego gift and warn you about mounting trials and softlocks the macro
![image](https://github.com/user-attachments/assets/c439a6db-f133-4571-9b77-de903248a1b2)

**Comment by KIYI671** [comment]
> When you confirm with 1/2 ego gifts, the game will ask if you want to pick another ego gift and warn you about mounting trials and softlocks the macro
> ![image](https://github.com/user-attachments/assets/c439a6db-f133-4571-9b77-de903248a1b2)

The reason why you need to select two EGO gifts is because you have selected Hard difficulty.AALC has already added the function of automatically switching to Normal difficulty in version V0.1.3.The reason why this problem still occurs may be due to the fact that:You manually selected the Hard difficulty yourself and started the script only after entering the Mirror dungeon, skipping the step of switching the difficulty automatically by AALC.
AALC has not added an adaptation for hard difficulty, so your current solutions are: manually finish the mirror dungeon and start the script on the main page; or just give up the adventure and start the script on the main page!

**Comment by misha1246** [comment]
My bad, thanks
