### ISSUE TITLE
Error "byte indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#6]
The script encounters an error in the shop when every character is at full health and sanity (it tries to skip, then stops working). Logs and video of the error are attached

[myLog.log](https://github.com/user-attachments/files/15856003/myLog.log)

https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/3c59c394-3878-4fe5-9f8e-f8a2f3383f9c

**Comment by KIYI671** [comment]
> The script encounters an error in the shop when every character is at full health and sanity (it tries to skip, then stops working). Logs and video of the error are attached
> 
> [myLog.log](https://github.com/user-attachments/files/15856003/myLog.log)
> 
> https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/3c59c394-3878-4fe5-9f8e-f8a2f3383f9c
> 
> 
> 
> 

One foreseen solution with this update is the problem of repeating the loop in this place and not being able to exit. However, since this is a relatively rare situation, I didn't actually test it, so I just tested it in my head to be able to fix it. I'm sorry for making this program buggy again, I'll fix it as soon as I can.

**Comment by KIYI671** [comment]
Hello， this issue has been fixed, please go to release to download the new script program update!
Thank you for your support of my program.
