### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#9]
Hello, I encountered an error during Ardor Blossom Moth fight. I think the Moth killed my character, the script recognized a dead character but couldn't revive him because dungeon event started

[2024-06-18.0001.debugLog.log](https://github.com/user-attachments/files/15881505/2024-06-18.0001.debugLog.log)
[2024-06-18.0001.debugLog.error.log](https://github.com/user-attachments/files/15881506/2024-06-18.0001.debugLog.error.log)

![7qjTdcUCWs4](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/038601e9-204e-4bd3-bebe-0fe50759500b)

**Comment by KIYI671** [comment]
> Hello, I encountered an error during Ardor Blossom Moth fight. I think the Moth killed my character, the script recognized a dead character but couldn't revive him because dungeon event started
> 
> [2024-06-18.0001.debugLog.log](https://github.com/user-attachments/files/15881505/2024-06-18.0001.debugLog.log)
> [2024-06-18.0001.debugLog.error.log](https://github.com/user-attachments/files/15881506/2024-06-18.0001.debugLog.error.log)
> 
> ![7qjTdcUCWs4](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/038601e9-204e-4bd3-bebe-0fe50759500b)
> 

The following text was translated by translation software.
Hello, it's a highly unlikely event that this occurs (I haven't encountered this in a hundred or two hundred mirror dungeons using the script myself) Normally it shouldn't be a problem, as the event will return to the battle at the end of the round, at which point the death of the culprit is detected, thus executing the exit from the battle program.
However, I'm guessing that this should happen because, having just automatically executed a round of combat, the character dies at the end of the round, and the script screenshot gets the information about the character's death the moment it enters a new round, and at the same time enters the event during the combat again. I have not set up a solution for when this happens, so it continues to execute the exit program because it can't find the exit button, resulting in an error quitting.
Please execute the event manually, then abort the battle and restart the script, this should be less common with this version of the script, and will be fixed in the future.
